### ISSUE TITLE
Unable to Register

### ISSUE THREAD

**Issue by vcanilkumar** [sumppen/WhatsApi4J#18]
Hi
I would like to know how to use Register API using the sample App
Looks like it is looking for the method where I have entered "Register" and code as 1111.

How will I get the code ?

Regards, Anil

$ register
Code: 1111
Event code_register_failed: phoneNumber=91XXXXXXXXXX
Caught exception: An error occurred registering the registration code from WhatsApp.
net.sumppen.whatsapi4j.WhatsAppException: An error occurred registering the registration code from WhatsApp.
        at net.sumppen.whatsapi4j.WhatsApi.codeRegister(WhatsApi.java:182)
        at net.sumppen.whatsapi4j.example.ExampleApplication.sendRegister(ExampleApplication.java:181)
        at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:136)

Regards, Anil

**Comment by sumppen** [comment]
Your server must have internet access, and a working DNS 

$ ping c.whatsapp.net
PING c.whatsapp.net (184.173.161.165): 56 data bytes
64 bytes from 184.173.161.165: icmp_seq=0 ttl=48 time=115.906 ms
64 bytes from 184.173.161.165: icmp_seq=1 ttl=48 time=114.264 ms
^C
--- c.whatsapp.net ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 114.264/115.085/115.906/0.821 ms

**Comment by rahulserver** [comment]
I think first we need to execute request command which would send an sms code to the mobile. We need to execute register after that and enter the code received via sms there instead of something random like 1111.

**Comment by vcanilkumar** [comment]
Hi

Question : How to receive the Code during the registration ?

I'm using the register command as below which is asking for the code.How to get the code

$ register
Code: 1234
Event code_register_failed: phoneNumber=<<MyNum>>
Caught exception: An error occurred registering the registration code from WhatsApp.
net.sumppen.whatsapi4j.WhatsAppException: An error occurred registering the registration code from WhatsApp.
        at net.sumppen.whatsapi4j.WhatsApi.codeRegister(WhatsApi.java:182)
        at net.sumppen.whatsapi4j.example.ExampleApplication.sendRegister(ExampleApplication.java:182)
        at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:137)
Event disconnect: phoneNumber=<<>>



I'm getting the following exception while using the  "Request" command


$ request
Caught exception: java.net.URISyntaxException: Illegal character in query at index 85: https://v.whatsapp.net/v2/code?cc=91&in=<<MyNUM>>&lg=hi&lc=IN&method=sms&sim_mcc=404|405|406&sim_mnc=000&token=b8965a1fabbe9c888db6bbf131139e36&id=%09%90%93%cd%9d%c9%0c%95%
9c%17%a8%86%05y%e6%40%e4+%0a%b3
javax.ws.rs.core.UriBuilderException: java.net.URISyntaxException: Illegal character in query at index 85: https://v.whatsapp.net/
v2/code?cc=91&in=<<MyNum>>&lg=hi&lc=IN&method=sms&sim_mcc=404|405|406&sim_mnc=000&token=b8965a1fabbe9c888db6bbf131139e36&id=%09%9
0%93%cd%9d%c9%0c%95%9c%17%a8%86%05y%e6%40%e4+%0a%b3
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.createURI(JerseyUriBuilder.java:909)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:884)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:810)
        at org.glassfish.jersey.client.JerseyWebTarget.getUri(JerseyWebTarget.java:135)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:223)
        at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:60)
        at net.sumppen.whatsapi4j.WhatsApi.getResponse(WhatsApi.java:2521)
        at net.sumppen.whatsapi4j.WhatsApi.codeRequest(WhatsApi.java:263)
        at net.sumppen.whatsapi4j.example.ExampleApplication.sendRequest(ExampleApplication.java:187)
        at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:129)
Caused by: java.net.URISyntaxException: Illegal character in query at index 85: https://v.whatsapp.net/v2/code?cc=91&in=<<MyNum>>
&lg=hi&lc=IN&method=sms&sim_mcc=404|405|406&sim_mnc=000&token=b8965a1fabbe9c888db6bbf131139e36&id=%09%90%93%cd%9d%c9%0c%95%9c%17%a
8%86%05y%e6%40%e4+%0a%b3
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.checkChars(URI.java:3002)
        at java.net.URI$Parser.parseHierarchical(URI.java:3092)
        at java.net.URI$Parser.parse(URI.java:3034)
        at java.net.URI.<init>(URI.java:595)
        at org.glassfish.jersey.uri.internal.JerseyUriBuilder.createURI(JerseyUriBuilder.java:907)




Regards, Anil
