### ISSUE TITLE
needed Libraries..

### ISSUE THREAD

**Issue by memin20** [sumppen/WhatsApi4J#25]
Hello,

i have a problem with the needed Jersey library. I have included the following libraries in the Build path:
- jersey-client-2.17.jar
- jersey-common-2.17.jar

But i get a NoClassDefFoundError Exception: 
Exception in thread "main" java.lang.NoClassDefFoundError: jersey/repackaged/com/google/common/base/Function
	at org.glassfish.jersey.client.ClientConfig$State.<init>(ClientConfig.java:147)
	at org.glassfish.jersey.client.ClientConfig.<init>(ClientConfig.java:457)
	at org.glassfish.jersey.client.JerseyClientBuilder.<init>(JerseyClientBuilder.java:94)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at java.lang.Class.newInstance0(Class.java:372)
	at java.lang.Class.newInstance(Class.java:325)
	at javax.ws.rs.client.FactoryFinder.newInstance(FactoryFinder.java:116)
	at javax.ws.rs.client.FactoryFinder.find(FactoryFinder.java:206)
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:86)
	at javax.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:114)
	at net.sumppen.whatsapi4j.WhatsApi.getResponse(WhatsApi.java:2505)
	at net.sumppen.whatsapi4j.WhatsApi.codeRequest(WhatsApi.java:263)
	at net.sumppen.whatsapi4j.example.ExampleApplication.sendRequest(ExampleApplication.java:228)
	at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:87)
Caused by: java.lang.ClassNotFoundException: jersey.repackaged.com.google.common.base.Function
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 17 more

**Comment by NirHUJI** [comment]
did you try to install the api using maven?

**Comment by sumppen** [comment]
The versions I've used are different, so it could be a version issue. If you try building it with maven ar NirHUJI suggested, you should get the correct version

**Comment by drenda** [comment]
I'm using it with maven whitout problems!

**Comment by memin20** [comment]
Ok, i had downloaded the zip file and found every library that was needed. Problem was solved with cloning the git repository. Thank you.
