### ISSUE TITLE
Catch in a graceful way network  problems

### ISSUE THREAD

**Issue by drenda** [sumppen/WhatsApi4J#33]
When there is a network problem the Thread messegePoller go into an infinite loop:

```java
16/04/2015 18:55:35,626 ERROR Thread-12 MessagePoller:25 - Message poller caught exception: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:154)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at net.sumppen.whatsapi4j.WhatsApi.readData(WhatsApi.java:2679)
	at net.sumppen.whatsapi4j.WhatsApi.pollMessages(WhatsApi.java:2955)
	at net.sumppen.whatsapi4j.MessagePoller.run(MessagePoller.java:22)
16/04/2015 18:55:35,651 ERROR Thread-12 MessagePoller:25 - Message poller caught exception: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:154)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at net.sumppen.whatsapi4j.WhatsApi.readData(WhatsApi.java:2679)
	at net.sumppen.whatsapi4j.WhatsApi.pollMessages(WhatsApi.java:2955)
	at net.sumppen.whatsapi4j.MessagePoller.run(MessagePoller.java:22)
16/04/2015 18:55:35,651 ERROR Thread-12 MessagePoller:25 - Message poller caught exception: Connection reset
```
Would be nice catch in a graceful way these problems and have the chance to recovery these errors and doing a reconnect() or something like that.

**Comment by sumppen** [comment]
Added catch to readData and send a disconnect event if this happens
