### ISSUE TITLE
How do i use this api ?

### ISSUE THREAD

**Issue by doriwal** [sumppen/WhatsApi4J#43]
public static void main(String[] args) {
		try{
		WhatsApi api = new WhatsApi(<my phone number>, "", <my name>);
		api.connect();
		api.sendMessage(<another phone number>, <some text>);
		}catch(Exception e){
			e.printStackTrace();
		}
	}

is this is how i should use the API ? I didnt get any message at  <another phone number> , but i see this output:

[main] INFO net.sumppen.whatsapi4j.LoggingEventManager - Event send_message: phoneNumber=<my phone number>

**Comment by elbano** [comment]
No, first you have to authenticate. You don't have the identity there (emei), are you sure you have the password for that line ? You have to register before you can use. After that you have to set the password. Look for the method loginWithPassword in WhatsApi.

**Comment by doriwal** [comment]
Thanks for quick response , yes i know that i am missing the register part , didnt understand how to do it 

if i understand it correct the flow is :


WhatsApi api = new WhatsApi("my phone number", "", "my name");
/* START one time flow to get the password */
api.codeRequest("sms", String countryCode, String langCode)
api.codeRegister(?) --> will return password
/* END one time flow to get the password */
api.loginWithPassword(password that i got from previews step)
api.connect();
api.sendMessage("another phone number", "some text");

**Comment by rahulserver** [comment]
If only a good demo is given, it would save a lot of time of people trying to make this api work(if at all it works!)

**Comment by doriwal** [comment]
there is a WhatsApi4J/src/main/java/net/sumppen/whatsapi4j/example/ExampleApplication.java
that i tried but i was not able to do anything 

a detailed example what is needed to do like how to get the code , how to register ... will help a lot

**Comment by rahulserver** [comment]
yeah
when I run this with username=91989009980, identity=myimeinumber,nickname=rahulserver and password=blank
I get this exception:
javax.ws.rs.core.UriBuilderException: java.net.URISyntaxException: Illegal character in query at index 85: https://v.whatsapp.net/v2/code?cc=91&in=8866894080&lg=hi&lc=IN&method=sms&sim_mcc=404|405|406&sim_mnc=000&token=0de2685816a2834c1f890a87b0d980ae&id=%10z%d0j%97%cb%b8%ab%a1%b441%f2r%96%7d8%bb%10%e6
Caught exception: java.net.URISyntaxException: Illegal character in query at index 85: https://v.whatsapp.net/v2/code?cc=91&in=8866894080&lg=hi&lc=IN&method=sms&sim_mcc=404|405|406&sim_mnc=000&token=0de2685816a2834c1f890a87b0d980ae&id=%10z%d0j%97%cb%b8%ab%a1%b441%f2r%96%7d8%bb%10%e6
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder.createURI(JerseyUriBuilder.java:909)
Event disconnect: phoneNumber=918866894080
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:884)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:810)
	at org.glassfish.jersey.client.JerseyWebTarget.getUri(JerseyWebTarget.java:135)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:223)
	at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:60)
	at net.sumppen.whatsapi4j.WhatsApi.getResponse(WhatsApi.java:2756)
	at net.sumppen.whatsapi4j.WhatsApi.codeRequest(WhatsApi.java:236)
	at net.sumppen.whatsapi4j.example.ExampleApplication.sendRequest(ExampleApplication.java:209)
	at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: java.net.URISyntaxException: Illegal character in query at index 85: https://v.whatsapp.net/v2/code?cc=91&in=8866894080&lg=hi&lc=IN&method=sms&sim_mcc=404|405|406&sim_mnc=000&token=0de2685816a2834c1f890a87b0d980ae&id=%10z%d0j%97%cb%b8%ab%a1%b441%f2r%96%7d8%bb%10%e6
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3092)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at org.glassfish.jersey.uri.internal.JerseyUriBuilder.createURI(JerseyUriBuilder.java:907)
	... 14 more


So the instructions on making this work are very incomplete, otherwise I am sure this would be one of the hottest repos on github!!

**Comment by sumppen** [comment]
Hi,

The problem I think is with the MCC. For some countries (India seems to be one) the MCC comes up with several values, which is sent as it is. This again makes the URL to be invalid

**Comment by rahulserver** [comment]
@sumppen I don't think its an issue with MCC. For my particular case, I found out the MCC and MNC from https://en.wikipedia.org/wiki/Mobile_country_code
(it was 404 and 05 for my case respectively.)
The steps given here https://github.com/tgalal/yowsup/wiki/yowsup-cli-2.0 
i.e. 
yowsup-cli registration --requestcode sms --phone 49XXXXXXXX --cc 49 --mcc 123 --mnc 456
yowsup-cli registration --register 123456 --phone 49XXXXXXXX --cc 49  

Are working well with me when I run via command line(on ubuntu). 
The phone.get("mcc") was giving 404|405|406 and since | is an invalid character, i was getting this exception.

But now when I manually change that value in query.put("sim_mcc","404");(whatsapi.java:231), I get this error:
net.sumppen.whatsapi4j.WhatsAppException: There was a problem trying to request the code. Status=fail
	at net.sumppen.whatsapi4j.WhatsApi.codeRequest(WhatsApi.java:250)
	at net.sumppen.whatsapi4j.example.ExampleApplication.sendRequest(ExampleApplication.java:390)
	at net.sumppen.whatsapi4j.example.ExampleApplication.main(ExampleApplication.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)


Not sure why thats happening, but yowsup works perfect and I get a confirmation sms in the request step. Hence this issue needs to be fixed.

**Comment by rahulserver** [comment]
@sumppen 
Further update on that exception. The JSONObject response(whatsapi.java 237) contains:
{"reason":"bad_token","status":"fail"}

So not sure why I am getting this bad token.

Here is the query.toString(), should you want to know exact params:
{cc=91, in=9809808760, lg=en, lc=IN, method=sms, sim_mcc=404, sim_mnc=05, token=7d54c6ae017aeb793945442184e41755, id=%10z%d0j%97%cb%b8%ab%a1%b441%f2r%96%7d8%bb%10%e6}

(in has been changed to some dummy number).

**Comment by klutzer** [comment]
#51
